"""add volunteers table

Revision ID: 202f8220cbc2
Revises: b1a2c3d4e5f6
Create Date: 2026-08-16 23:23:10.629945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202f8220cbc2'
down_revision = 'b1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('country_of_residence', sa.String(length=100), nullable=True),
    sa.Column('passport_number', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('emergency_full_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_relationship', sa.String(length=100), nullable=True),
    sa.Column('emergency_country', sa.String(length=100), nullable=True),
    sa.Column('emergency_phone', sa.String(length=100), nullable=True),
    sa.Column('emergency_email', sa.String(length=255), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('other_program', sa.String(length=500), nullable=True),
    sa.Column('arrival_date', sa.String(length=50), nullable=True),
    sa.Column('departure_date', sa.String(length=50), nullable=True),
    sa.Column('length_of_stay', sa.String(length=100), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('educational_background', sa.Text(), nullable=True),
    sa.Column('professional_experience', sa.Text(), nullable=True),
    sa.Column('technical_skills', sa.Text(), nullable=True),
    sa.Column('languages_spoken', sa.String(length=500), nullable=True),
    sa.Column('previous_volunteer_experience', sa.Text(), nullable=True),
    sa.Column('relevant_certifications', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('hope_to_learn', sa.Text(), nullable=True),
    sa.Column('contribution', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('dietary_requirements', sa.String(length=255), nullable=True),
    sa.Column('emergency_medical_info', sa.Text(), nullable=True),
    sa.Column('need_accommodation', sa.String(length=10), nullable=True),
    sa.Column('room_preference', sa.String(length=50), nullable=True),
    sa.Column('need_invitation_letter', sa.String(length=10), nullable=True),
    sa.Column('need_airport_pickup', sa.String(length=10), nullable=True),
    sa.Column('expected_arrival_airport', sa.String(length=255), nullable=True),
    sa.Column('flight_details', sa.Text(), nullable=True),
    sa.Column('media_consent', sa.String(length=10), nullable=True),
    sa.Column('code_of_conduct', sa.JSON(), nullable=True),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('applicant_name_declaration', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('declaration_date', sa.String(length=50), nullable=True),
    sa.Column('passport_copy_url', sa.String(length=500), nullable=True),
    sa.Column('passport_photo_url', sa.String(length=500), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('motivation_letter_url', sa.String(length=500), nullable=True),
    sa.Column('recommendation_letter_url', sa.String(length=500), nullable=True),
    sa.Column('certificates_url', sa.String(length=500), nullable=True),
    sa.Column('hours_logged', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')

    op.drop_table('volunteers')
    # ### end Alembic commands ###
