"""Add enhanced district fields and ImpactStory model

Revision ID: 6cc94a73126b
Revises: 76be96e2cac6
Create Date: 2026-06-20 15:59:43.455312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc94a73126b'
down_revision = '76be96e2cac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: skip columns that already exist (e.g. schema created via
    # db.create_all() before migrations were introduced).
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = {col["name"] for col in inspector.get_columns("district_metrics")}

    with op.batch_alter_table('district_metrics', schema=None) as batch_op:
        if 'province' not in existing:
            batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False, server_default='Eastern Province'))
        if 'province_key' not in existing:
            batch_op.add_column(sa.Column('province_key', sa.String(length=20), nullable=False, server_default='east'))
        if 'description' not in existing:
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        if 'species' not in existing:
            batch_op.add_column(sa.Column('species', sa.JSON(), nullable=True))
        if 'map_coords_x' not in existing:
            batch_op.add_column(sa.Column('map_coords_x', sa.Float(), nullable=True))
        if 'map_coords_y' not in existing:
            batch_op.add_column(sa.Column('map_coords_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_metrics', schema=None) as batch_op:
        batch_op.drop_column('map_coords_y')
        batch_op.drop_column('map_coords_x')
        batch_op.drop_column('species')
        batch_op.drop_column('description')
        batch_op.drop_column('province_key')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
