"""Add completion_count to WeeklyChallenge

Revision ID: 76be96e2cac6
Revises: a26889b0b99a
Create Date: 2026-06-20 15:04:32.127227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76be96e2cac6'
down_revision = 'a26889b0b99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.drop_column('completion_count')

    # ### end Alembic commands ###
