"""Add is_external and external_url to opportunities

Revision ID: a26889b0b99a
Revises: 
Create Date: 2026-06-20 13:29:45.823885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26889b0b99a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('external_url')
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
