"""Add is_external and external_url to opportunities

Revision ID: a26889b0b99a
Revises: 
Create Date: 2026-06-20 13:29:45.823885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26889b0b99a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: skip columns that already exist. This handles databases that
    # were previously created with db.create_all() (which already includes
    # these columns), so `flask db upgrade` won't fail with DuplicateColumn.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = {col["name"] for col in inspector.get_columns("opportunities")}

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        if 'is_external' not in existing:
            batch_op.add_column(sa.Column('is_external', sa.Boolean(), server_default='0', nullable=False))
        if 'external_url' not in existing:
            batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('external_url')
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
